version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ethpayserver
      - MYSQL_USER=ethpayserver
      - MYSQL_PASSWORD=123456
    volumes:
      - ethpay_mysql:/var/lib/mysql
    ports:
      - 6033:3306

volumes:
  ethpayserver_mysql:
